[Dialogs]
UserInfo=0
FeatureInfo1=1
SingleDirectory=1
InstallationType=0
FeatureTree=0
License=0
License2=1
NICertificate=0
WinFastStartup=1
ConfirmStart=1
End=1

[Distribution]
Title=1
GUID={0897B4B8-3651-41FF-A51E-98211D8A4E36}
PackageGUID={D536D111-73D5-4196-A233-D8EBF560B12D}
Version=1.0.0
IDPath=nidist.id
Has64bitPart=1

[EndDialog]
Readme=5;30,50,330,150;static

[Files]
License2TextFile0009=NI;license\NI Released License Agreement - English.rtf
License2TextFile0010=NI;license\NI Released License Agreement - Spanish.rtf
License2TextFile0016=NI;license\NI Released License Agreement - Italian.rtf
License2TextFile0007=NI;license\NI Released License Agreement - German.rtf
License2TextFile0012=NI;license\NI Released License Agreement - French.rtf
License2TextFile0017=NI;license\NI Released License Agreement - Japanese.rtf
License2TextFile0018=NI;license\NI Released License Agreement - Korean.rtf
License2TextFile2052=NI;license\NI Released License Agreement - Simplified Chinese.rtf

[Graphics]
TopBar=IDB_TOPSTRIP,IDB_LARGETOPSTRIP
FullScreen=IDB_FULLSCREEN,IDB_LARGEFULLSCREEN

[InitProgress]
left=55
top=165
right=340
bottom=179
red=206
green=203
blue=173

[InstallLevels]
Default=100

[Localization]
Languages=17
ForceLanguage=17
StandardRes0017=supportfiles\nires0017.dll
CustomRes0017=supportfiles\customResource0017.dll
StandardLangXfm0007=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0007.mst
StandardLangXfm0012=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0012.mst
StandardLangXfm0017=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0017.mst
StandardLangXfm0018=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0018.mst
StandardLangXfm2052=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans2052.mst

[Merged]
Path=supportfiles\merged.cab

[OS]
VersionNTMin=5,1,2600,3,0
VersionNTMax=

[Settings]
WelcomeAutoAdvance=1

[SingleDirectoryDialog]
DirText1=4
DirText2=7
Dir1=INSTALLDIR.MDF100
Dir1EditLabel=8
Dir2=NIDIR
Dir2EditLabel=9

[WinFastStartupDialog]
CheckboxDefaultState=1

[Strings]
WelcomeTitle=2;15,20,260,45
WelcomeText=3;15,55,260,115

[Utilities]
UpgradeManagerPostProcessor=supportfiles\niPie.exe

[Parts]
LV2013runtime.msi=
LV2013rtdnet.msi=
MetaUninstaller.msi=
MDFSupport.msi=
EulaDepot.msi=
CVI_LowLevelDriverOriginal.msi=
CVI_LowLevelDriverUpdated.msi=
LV2013rteres.msi=
activex.msi=
activex64.msi=
ni_syswebsrvr.msi=
mkl.msi=
mkl64.msi=
logos.msi=
logos64.msi=
tdms.msi=
tdms64.msi=
NIWebServer_LVRTE.msi=
LVRT_NBFifo_2013.msi=
NITraceEngine.msi=
NITraceEngine64.msi=
VC2008MSMs_x86.msi=
VC2008MSMs_x64.msi=
mDNSResponder.msi=
mDNSResponder_W64.msi=
dep_framework.msi=
ni_error_report.msi=
MStudioCW3DGraph.msi=
KillBit.msi=
KillBit64.msi=
ni_sysweb_base.msi=
ni_sysweb_base64.msi=
ni_sysappsrvr.msi=
ni_sysappsrvr64.msi=
nisvcloc.msi=
LogosXT.msi=
LogosXT64.msi=
NI_SysStatePub.msi=
NI_SysStatePub64.msi=
ssl_LVRTEsupp.msi=
ni_ssl.msi=
ni_ssl64.msi=
niauth.msi=
niauth64.msi=
nicurl.msi=
nicurl64.msi=
ni_gmp.msi=
ni_gmp64.msi=
install.msi=
[LV2013runtime.msi]
Path=bin\p27\LV2013runtime.msi
Volume=1
ProductCode={C0446EC0-D69F-44C3-B3AD-E04EA7FAE72B}
ProductId={C0446EC0-D69F-44C3-B3AD-E04EA7FAE72B}
LangXfm0007=bin\p27\lvrte_deu.mst
LangXfm0012=bin\p27\lvrte_fra.mst
LangXfm0017=bin\p27\lvrte_jpn.mst
LangXfm0018=bin\p27\lvrte_kor.mst
LangXfm2052=bin\p27\lvrte_chs.mst
[LV2013rtdnet.msi]
Path=bin\p27\LV2013rtdnet.msi
Volume=1
ProductCode={2931F00C-6417-4BFE-B3C5-26D90ABE8189}
[MetaUninstaller.msi]
Path=bin\p0\MU\MetaUninstaller.msi
Volume=1
ProductCode={4416E546-A113-4B37-9FA5-C5165EEF36E0}
ProductId={4416E546-A113-4B37-9FA5-C5165EEF36E0}
[MDFSupport.msi]
Path=bin\p24\MDF\MDFSupport.msi
Volume=1
ProductCode={4E45B56F-95B5-4A1D-B5CC-B410FF1726AE}
ProductId={4E45B56F-95B5-4A1D-B5CC-B410FF1726AE}
[EulaDepot.msi]
Path=bin\p24\MDF\EulaDepot.msi
Volume=1
ProductCode={97401357-96F5-45D0-8CC3-2031EE48B8C0}
[CVI_LowLevelDriverOriginal.msi]
Path=bin\p4\CVI_LowLevelDriverOriginal.msi
Volume=1
ProductCode={2B1D39F8-477A-4B40-B062-F5E0C4D42B9B}
ProductId={2B1D39F8-477A-4B40-B062-F5E0C4D42B9B}
[CVI_LowLevelDriverUpdated.msi]
Path=bin\p4\CVI_LowLevelDriverUpdated.msi
Volume=1
ProductCode={74DBB98D-B4A7-4DD9-9E13-C51FDB1105D0}
[LV2013rteres.msi]
Path=bin\p25\lvrteres\LV2013rteres.msi
Volume=1
ProductCode={9BA381D6-F63D-4C03-BE13-940F39068E01}
ProductId={9BA381D6-F63D-4C03-BE13-940F39068E01}
LangXfm0007=bin\p25\lvrteres\lvrteres_deu.mst
LangXfm0012=bin\p25\lvrteres\lvrteres_fra.mst
LangXfm0017=bin\p25\lvrteres\lvrteres_jpn.mst
LangXfm0018=bin\p25\lvrteres\lvrteres_kor.mst
LangXfm2052=bin\p25\lvrteres\lvrteres_chs.mst
[activex.msi]
Path=bin\p19\activex.msi
Volume=1
ProductCode={53606225-A1A8-4A74-BA4B-00206F38DB60}
ProductId={53606225-A1A8-4A74-BA4B-00206F38DB60}
LangXfm0007=bin\p19\activ32_deu.mst
LangXfm0012=bin\p19\activ32_fra.mst
LangXfm0017=bin\p19\activ32_jpn.mst
LangXfm0018=bin\p19\activ32_kor.mst
LangXfm2052=bin\p19\activ32_chs.mst
[activex64.msi]
Path=bin\p19\activex64.msi
Volume=1
ProductCode={63B6ADAB-AB1B-4542-911D-C15FFBD5E1BE}
LangXfm0007=bin\p19\activ64_deu.mst
LangXfm0012=bin\p19\activ64_fra.mst
LangXfm0017=bin\p19\activ64_jpn.mst
LangXfm0018=bin\p19\activ64_kor.mst
LangXfm2052=bin\p19\activ64_chs.mst
[ni_syswebsrvr.msi]
Path=bin\p14\sys_w00\ni_syswebsrvr.msi
Volume=1
ProductCode={FC59A893-A510-411A-A71C-60A06D2C9BF2}
ProductId={FC59A893-A510-411A-A71C-60A06D2C9BF2}
LangXfm0007=bin\p14\sys_w00\sys_w00_deu.mst
LangXfm0012=bin\p14\sys_w00\sys_w00_fra.mst
LangXfm0017=bin\p14\sys_w00\sys_w00_jpn.mst
LangXfm0018=bin\p14\sys_w00\sys_w00_kor.mst
LangXfm2052=bin\p14\sys_w00\sys_w00_chs.mst
[mkl.msi]
Path=bin\p23\mkl.msi
Volume=1
ProductCode={E71784F9-5B67-4052-A5FC-55C038396936}
ProductId={E71784F9-5B67-4052-A5FC-55C038396936}
LangXfm0007=bin\p23\MKL2013_deu.mst
LangXfm0012=bin\p23\MKL2013_fra.mst
LangXfm0017=bin\p23\MKL2013_jpn.mst
LangXfm0018=bin\p23\MKL2013_kor.mst
LangXfm2052=bin\p23\MKL2013_chs.mst
[mkl64.msi]
Path=bin\p23\mkl64.msi
Volume=1
ProductCode={112D8201-03A2-43B2-861B-EB3FCB855547}
LangXfm0007=bin\p23\MKL2000_deu.mst
LangXfm0012=bin\p23\MKL2000_fra.mst
LangXfm0017=bin\p23\MKL2000_jpn.mst
LangXfm0018=bin\p23\MKL2000_kor.mst
LangXfm2052=bin\p23\MKL2000_chs.mst
[logos.msi]
Path=bin\p26\logos.msi
Volume=1
ProductCode={CA533BA0-E6F9-4349-B0EC-ABDEB0481E77}
ProductId={CA533BA0-E6F9-4349-B0EC-ABDEB0481E77}
LangXfm0007=bin\p26\logos_deu.mst
LangXfm0012=bin\p26\logos_fra.mst
LangXfm0017=bin\p26\logos_jpn.mst
LangXfm0018=bin\p26\logos_kor.mst
LangXfm2052=bin\p26\logos_chs.mst
[logos64.msi]
Path=bin\p26\logos64.msi
Volume=1
ProductCode={B2149E16-A01C-458E-A6E5-B9DC96EAD1AA}
LangXfm0007=bin\p26\logos64_deu.mst
LangXfm0012=bin\p26\logos64_fra.mst
LangXfm0017=bin\p26\logos64_jpn.mst
LangXfm0018=bin\p26\logos64_kor.mst
LangXfm2052=bin\p26\logos64_chs.mst
[tdms.msi]
Path=bin\p20\tdms.msi
Volume=1
ProductCode={27367777-A95D-4014-B73B-18D4838E54A4}
ProductId={27367777-A95D-4014-B73B-18D4838E54A4}
LangXfm0007=bin\p20\tdms_deu.mst
LangXfm0012=bin\p20\tdms_fra.mst
LangXfm0017=bin\p20\tdms_jpn.mst
LangXfm0018=bin\p20\tdms_kor.mst
LangXfm2052=bin\p20\tdms_chs.mst
[tdms64.msi]
Path=bin\p20\tdms64.msi
Volume=1
ProductCode={3ABCF186-64DE-439C-8B66-CC31B8513D8C}
LangXfm0007=bin\p20\tdms64_deu.mst
LangXfm0012=bin\p20\tdms64_fra.mst
LangXfm0017=bin\p20\tdms64_jpn.mst
LangXfm0018=bin\p20\tdms64_kor.mst
LangXfm2052=bin\p20\tdms64_chs.mst
[NIWebServer_LVRTE.msi]
Path=bin\p16\LVRTE00\NIWebServer_LVRTE.msi
Volume=1
ProductCode={ADC16943-45BD-4E47-89CD-A9CA790DE09C}
ProductId={ADC16943-45BD-4E47-89CD-A9CA790DE09C}
LangXfm0007=bin\p16\LVRTE00\LVRTE00_deu.mst
LangXfm0012=bin\p16\LVRTE00\LVRTE00_fra.mst
LangXfm0017=bin\p16\LVRTE00\LVRTE00_jpn.mst
LangXfm0018=bin\p16\LVRTE00\LVRTE00_kor.mst
LangXfm2052=bin\p16\LVRTE00\LVRTE00_chs.mst
[LVRT_NBFifo_2013.msi]
Path=bin\p10\LVRT_00\LVRT_NBFifo_2013.msi
Volume=1
ProductCode={EEDB0927-3BD8-4349-856E-425A146CC680}
ProductId={EEDB0927-3BD8-4349-856E-425A146CC680}
LangXfm0007=bin\p10\LVRT_00\LVRT_00_deu.mst
LangXfm0012=bin\p10\LVRT_00\LVRT_00_fra.mst
LangXfm0017=bin\p10\LVRT_00\LVRT_00_jpn.mst
LangXfm0018=bin\p10\LVRT_00\LVRT_00_kor.mst
LangXfm2052=bin\p10\LVRT_00\LVRT_00_chs.mst
[NITraceEngine.msi]
Path=bin\p7\NITraceEngine.msi
Volume=1
ProductCode={63495F25-850C-4127-8BA6-1DFD5144723C}
ProductId={63495F25-850C-4127-8BA6-1DFD5144723C}
[NITraceEngine64.msi]
Path=bin\p7\NITraceEngine64.msi
Volume=1
ProductCode={DA83B4AC-EC3C-4F13-A867-CB0C24A8E1D5}
[VC2008MSMs_x86.msi]
Path=bin\p1\VC2008MSMs\VC2008MSMs_x86.msi
Volume=1
ProductCode={E84997A1-4D6F-4C0B-B60D-F85B360D2666}
ProductId={E84997A1-4D6F-4C0B-B60D-F85B360D2666}
[VC2008MSMs_x64.msi]
Path=bin\p1\VC2008MSMs\VC2008MSMs_x64.msi
Volume=1
ProductCode={07E00E94-7A78-40FA-9BEF-71C190E98041}
[mDNSResponder.msi]
Path=bin\p6\mDNSResponder.msi
Volume=1
ProductCode={1F7F5330-D1C5-49D8-85A3-75E29C2434FE}
ProductId={1F7F5330-D1C5-49D8-85A3-75E29C2434FE}
[mDNSResponder_W64.msi]
Path=bin\p6\mDNSResponder_W64.msi
Volume=1
ProductCode={3A6898F6-9B23-40DE-9B2D-617DBDEFDBF9}
[dep_framework.msi]
Path=bin\p3\NI_De00\dep_framework.msi
Volume=1
ProductCode={EE372D3C-8CDE-4141-8DE9-05A0734B63E4}
ProductId={EE372D3C-8CDE-4141-8DE9-05A0734B63E4}
[ni_error_report.msi]
Path=bin\p17\ni_error\ni_error_report.msi
Volume=1
ProductCode={DF549FB9-B94F-4B8D-B007-39281EDB9A52}
ProductId={DF549FB9-B94F-4B8D-B007-39281EDB9A52}
LangXfm0007=bin\p17\ni_error\ni_error_deu.mst
LangXfm0012=bin\p17\ni_error\ni_error_fra.mst
LangXfm0017=bin\p17\ni_error\ni_error_jpn.mst
LangXfm0018=bin\p17\ni_error\ni_error_kor.mst
LangXfm2052=bin\p17\ni_error\ni_error_chs.mst
[MStudioCW3DGraph.msi]
Path=bin\p28\MStudioCW3DGraph.msi
Volume=1
ProductCode={F278392D-547E-4E67-AD1C-2576C2852B50}
ProductId={F278392D-547E-4E67-AD1C-2576C2852B50}
[KillBit.msi]
Path=bin\p5\KillBit.msi
Volume=1
ProductCode={20124E21-206B-485F-838F-14BB88161045}
ProductId={20124E21-206B-485F-838F-14BB88161045}
[KillBit64.msi]
Path=bin\p5\KillBit64.msi
Volume=1
ProductCode={4A78D9E6-D349-4CCA-9295-45B12BE5BC6C}
[ni_sysweb_base.msi]
Path=bin\p18\ni_sysweb_base.msi
Volume=1
ProductCode={69D447B3-1B3F-42A9-9605-A8533BE06D17}
ProductId={69D447B3-1B3F-42A9-9605-A8533BE06D17}
[ni_sysweb_base64.msi]
Path=bin\p18\ni_sysweb_base64.msi
Volume=1
ProductCode={A0133B57-1D4B-4D89-A0EF-1453ECECA58A}
[ni_sysappsrvr.msi]
Path=bin\p22\ni_sysappsrvr.msi
Volume=1
ProductCode={4845B7A3-DDC3-44F9-A7DB-C50C94017129}
ProductId={4845B7A3-DDC3-44F9-A7DB-C50C94017129}
LangXfm0007=bin\p22\sys_a01_deu.mst
LangXfm0012=bin\p22\sys_a01_fra.mst
LangXfm0017=bin\p22\sys_a01_jpn.mst
LangXfm0018=bin\p22\sys_a01_kor.mst
LangXfm2052=bin\p22\sys_a01_chs.mst
[ni_sysappsrvr64.msi]
Path=bin\p22\ni_sysappsrvr64.msi
Volume=1
ProductCode={62126BD1-8107-48A1-9889-FA16F064893C}
LangXfm0007=bin\p22\sys_a00_deu.mst
LangXfm0012=bin\p22\sys_a00_fra.mst
LangXfm0017=bin\p22\sys_a00_jpn.mst
LangXfm0018=bin\p22\sys_a00_kor.mst
LangXfm2052=bin\p22\sys_a00_chs.mst
[nisvcloc.msi]
Path=bin\p13\svcloc\nisvcloc.msi
Volume=1
ProductCode={23180501-7886-47B6-AB6E-5ABFB1848012}
ProductId={23180501-7886-47B6-AB6E-5ABFB1848012}
LangXfm0007=bin\p13\svcloc\svcloc_deu.mst
LangXfm0012=bin\p13\svcloc\svcloc_fra.mst
LangXfm0017=bin\p13\svcloc\svcloc_jpn.mst
LangXfm0018=bin\p13\svcloc\svcloc_kor.mst
LangXfm2052=bin\p13\svcloc\svcloc_chs.mst
[LogosXT.msi]
Path=bin\p15\LogosXT.msi
Volume=1
ProductCode={A05EFB3F-19E2-4F9E-8380-BE095CCF0BE4}
ProductId={A05EFB3F-19E2-4F9E-8380-BE095CCF0BE4}
[LogosXT64.msi]
Path=bin\p15\LogosXT64.msi
Volume=1
ProductCode={A3154334-4692-449E-8836-3CCD28D0B1D7}
[NI_SysStatePub.msi]
Path=bin\p8\NI_SysStatePub.msi
Volume=1
ProductCode={AE20D525-5D10-475F-9115-963DB67D49DF}
ProductId={AE20D525-5D10-475F-9115-963DB67D49DF}
[NI_SysStatePub64.msi]
Path=bin\p8\NI_SysStatePub64.msi
Volume=1
ProductCode={68319FE7-1E06-4156-BC00-8D24828B5084}
[ssl_LVRTEsupp.msi]
Path=bin\p2\sslLVRTE\ssl_LVRTEsupp.msi
Volume=1
ProductCode={BF324FB5-4C39-4FDC-B023-19AEFFAE116A}
ProductId={BF324FB5-4C39-4FDC-B023-19AEFFAE116A}
[ni_ssl.msi]
Path=bin\p21\ni_ssl.msi
Volume=1
ProductCode={87392509-BFBD-4780-9170-E0106DB472DF}
ProductId={87392509-BFBD-4780-9170-E0106DB472DF}
LangXfm0007=bin\p21\ssl_deu.mst
LangXfm0012=bin\p21\ssl_fra.mst
LangXfm0017=bin\p21\ssl_jpn.mst
LangXfm0018=bin\p21\ssl_kor.mst
LangXfm2052=bin\p21\ssl_chs.mst
[ni_ssl64.msi]
Path=bin\p21\ni_ssl64.msi
Volume=1
ProductCode={A6E0DCE3-A917-4234-B401-6D630E869FB3}
LangXfm0007=bin\p21\ssl64_deu.mst
LangXfm0012=bin\p21\ssl64_fra.mst
LangXfm0017=bin\p21\ssl64_jpn.mst
LangXfm0018=bin\p21\ssl64_kor.mst
LangXfm2052=bin\p21\ssl64_chs.mst
[niauth.msi]
Path=bin\p11\niauth.msi
Volume=1
ProductCode={6CB3DA3D-C753-423D-AB3B-670C5C2FE6C4}
ProductId={6CB3DA3D-C753-423D-AB3B-670C5C2FE6C4}
[niauth64.msi]
Path=bin\p11\niauth64.msi
Volume=1
ProductCode={2BF63B6D-6B44-46D5-8F2C-5BFBC78D9593}
[nicurl.msi]
Path=bin\p12\nicurl.msi
Volume=1
ProductCode={2DD33997-3C3E-4517-9D98-0CC5802D6D53}
ProductId={2DD33997-3C3E-4517-9D98-0CC5802D6D53}
[nicurl64.msi]
Path=bin\p12\nicurl64.msi
Volume=1
ProductCode={E957A395-E199-4B35-B06A-FF7CBA66B953}
[ni_gmp.msi]
Path=bin\p9\ni_gmp.msi
Volume=1
ProductCode={0AF8A008-7141-40DD-BB99-10B7F0C4769A}
ProductId={0AF8A008-7141-40DD-BB99-10B7F0C4769A}
[ni_gmp64.msi]
Path=bin\p9\ni_gmp64.msi
Volume=1
ProductCode={00D12A70-7B79-4A14-80B5-F12626237DE7}
[install.msi]
Path=bin\dp\install.msi
Volume=1
ProductCode={B08C0EA9-B17B-4BE8-A8F7-9D53A58C793A}
ProductId={B08C0EA9-B17B-4BE8-A8F7-9D53A58C793A}
[LicenseTypes]
LicenseType2=NIStandardReleased
LicenseType3=Apache20
LicenseType4=Boost
LicenseType5=BSD3Clause
LicenseType6=CryptoPP
LicenseType7=FreeType
LicenseType8=LGPL
LicenseType9=LGPL300
LicenseType10=LLVM
LicenseType11=MARS
LicenseType12=MicrosoftPublicLicense
LicenseType13=MIT
LicenseType14=MIT-X-YAJL
LicenseType15=MIT-X
LicenseType16=Mozilla20
LicenseType17=NICTA
LicenseType18=OpenSSL
LicenseType19=UPX
LicenseType20=wxWindows
LicenseType21=WordNet21
LicenseType22=zlib
[LicenseType2]
IsDisplayedAlone=0
IsThirdParty=0
IsHideInMetaSuite=0
[LicenseType3]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType4]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType5]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType6]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType7]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType8]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType9]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType10]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType11]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType12]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType13]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType14]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType15]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType16]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType17]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType18]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType19]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType20]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType21]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType22]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[SilentInstallRequirements]
MustAcceptLicenses=1
[MDF]
MDFVersion=3.2.0.351
HasPatchSupport=0
DevPartSection=install.msi
